### ISSUE TITLE
Push code to repository with instructions on how to set up the development environment

### ISSUE THREAD

**Issue by ginic** [UMassCDS/ds4cg2024-inaturalist#17]
Goal: Create a repository for annotation tool that other developers can use to add features or work on

Definition of Done: 
- [x] All code related to the app/annotation tool should be in its own repo (ds4cg2024-inaturalist repo)
- [x] README includes installation instructions 
- [x] React packaging requirements 
- [x] Set code standards for library and include them in documentation
- [ ] Have meeting with team to do a code review
- [ ] ~~Pick one version of prototype code to use as a starting point on the main branch~~ **-> reassigned to Sergei**
- [ ] ~~Copy code from SINR repo that's needed (few functions that are needed)~~ **-> reassigned to Sergei**
- [ ] ~~Add prototype code~~ **-> reassigned to Sergei**

**Comment by oz03-hub** [comment]
Re-opened to add docker setup instructions
