### ISSUE TITLE
Annotators can individually change predictions in hexes at resolution level 5 and save them

### ISSUE THREAD

**Issue by ginic** [UMassCDS/ds4cg2024-inaturalist#20]
As an ecologist, I need to be able to select a single hex and change its value for whether the species is predicted there or not. 

- Cells where the model predicts the species to be are initially colored in
- Clicking a hex flips whether the species range is there or not
- There is a clear visual distinction between hexes that are predicted within the species range and those that are not.
- The user will click a "Save" button that export JSON (later on this button will populates the changes in the database). No changes are saved until they click that button 

Definition of done:
- [x] Hexagon grid at resolution 5 is displayed in the map as a base layer
- [x] OPTIONAL: After certain zoom, grid is no longer displayed 
- [x] When getting prediction, the annotation layer is created, showing in a different color (green) the corresponding res-5-hexagon. This will be the annotation starting point (if the user submits annotation without changes, then their annotation coincides with the model prediction)
- [x] User can click on hexagons and this action changes colors of the hexagons (select and unselect)
- [x] We are keeping track somehow of selected hexagons so they can be stored in a json file by the end of the annotation.

**Comment by oz03-hub** [comment]
I made a separate branch from hex, I am trying to add dynamic rendering of hexagons, like when you navigate map it will render automatically without clicking a button

**Comment by oz03-hub** [comment]
I was able to make dynamic hexagon generation, code might be a little messy, I will publish my branch shortly, you can take a look @cheerstopaula

**Comment by oz03-hub** [comment]
Definition of done:

[x] Hexagon grid at resolution 5 is displayed in the map as a base layer
[x] OPTIONAL: After certain zoom, grid is no longer displayed
[] When getting prediction, the annotation layer is created, showing in a different color (green) the corresponding res-5-hexagon. This will be the annotation starting point (if the user submits annotation without changes, then their annotation coincides with the model prediction)
[x] User can click on hexagons and this action changes colors of the hexagons (select and unselect)
[x] We are keeping track somehow of selected hexagons so they can be stored in a json file by the end of the annotation.
