### ISSUE TITLE
Github workflow to push Docker containers to CDS DockerHub for tagged releases

### ISSUE THREAD

**Issue by ginic** [UMassCDS/ds4cg2024-inaturalist#26]
As a developer, I would like Docker containers to be built for official releases using CICD workflows on Github so that I can more easily share and deploy the application. 

This will involve both gathering team input to decide when and how releases should be created, as well as setting up Github workflows and documentation. 

Definition of Done:
- [x] Research best practices on creating releases (start with https://zeet.co/blog/software-release-management-best-practices and https://semver.org/). Present different options and their trade-offs to the team. Reach a consensus agreement with the team on the steps that should be taken to create releases. 
- [x] Create Contribution guidelines for the repository that explain the release process and lists the steps that need to be taken when creating a release. 
- [x] Work with Virginia to add the umasscds DockerHub credentials to the Github repo
- [ ] Create a CICD workflow that builds, tags and pushes Docker containers to DockerHub when a new release is created (see https://github.com/UMassCDS/satellite-imagery-labeling-tool/blob/containerization/.github/workflows/create-docker-images.yml for an example)

**Comment by angelazhu2** [comment]
code contribution guidelines: https://docs.google.com/document/d/1mmtoM0A6rzxzdRF4vvQqHb4UGrG0Zl-nBEugV4Pi8oI/edit?usp=sharing
