### ISSUE TITLE
Remove copied SINR code from the respository

### ISSUE THREAD

**Issue by ginic** [UMassCDS/ds4cg2024-inaturalist#28]
As a developer, I need our application to be easy to maintain, so that I have time to work on new features and not just repository maintenance. Having copied code from a different repository makes a project much more difficult to maintain for these reasons: 
- It makes reviewing code and comparing code difficult, because it is difficult to tell which changes are from which repository. 
- It creates additional maintenance overhead. Every time the code in the copied repo is changed on git, I need to first find out about it, then recopy the code to my repository. 

There are two options here: 
Option 1) Add the SINR code as a git submodule (see https://www.freecodecamp.org/news/how-to-use-git-submodules/)
Option 2) Convert the SINR code to a proper python package that can be installed via the requirements.txt file (note that it doesn't need to be pushed to pypi, see https://pip.pypa.io/en/stable/topics/vcs-support/)

**Comment by angelazhu2** [comment]
linked to prototype pr: https://github.com/UMassCDS/ds4cg2024-inaturalist/pull/25/files#diff-d1bfd7459bf41ce7af92b21f4e8981dcea885fec67097986ba7aaf58d1b49916
